# Generated by Django 5.2.8 on 2025-12-13 06:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_code', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hook', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userhome', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('favcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Homes.favoritecart')),
                ('homes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homes.home')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Homes.home')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('RENTER/BUYER', 'Rernter/Buyer'), ('SELLER', 'Seller'), ('AGENT', 'Agent')], max_length=50)),
                ('name_user', models.CharField(max_length=12)),
                ('phone_number', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '900000000'. Up to 9 digits allowed.", regex='^\\d{9}$')])),
                ('city', models.CharField(choices=[('TASHKENT', 'Tashkent'), ('SAMARKAND', 'Samarkand'), ('BUKHARA', 'Bukhara'), ('NUKUS', 'Nukus'), ('ANDIJAN', 'Andijan'), ('NAMANGAN', 'Namangan'), ('GERGANA', 'Fergana'), ('KOKAND', 'Kokand'), ('KARSHI', 'Karshi'), ('NAVOIY', 'Navoiy'), ('TERMIZ', 'Termiz'), ('JIZZAH', 'Jizzah')], max_length=50)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
