# Generated by Django 5.2.8 on 2025-12-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='name',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='home',
            name='hook',
        ),
        migrations.AddField(
            model_name='home',
            name='bathrooms_descrip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='bedrooms_descrip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='city',
            field=models.CharField(choices=[('TASHKENT', 'Tashkent'), ('SAMARKAND', 'Samarkand'), ('BUKHARA', 'Bukhara'), ('NUKUS', 'Nukus'), ('ANDIJAN', 'Andijan'), ('NAMANGAN', 'Namangan'), ('GERGANA', 'Fergana'), ('KOKAND', 'Kokand'), ('KARSHI', 'Karshi'), ('NAVOIY', 'Navoiy'), ('TERMIZ', 'Termiz'), ('JIZZAH', 'Jizzah')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='kitchen_descrip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='livingroom_descrip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
    ]
