# Generated by Django 6.0.2 on 2026-04-17 14:12

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension
from django.contrib.postgres.indexes import GinIndex

class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0002_rename_name_home_district_remove_home_hook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='home',
             index=GinIndex(
                fields=['district'],
                name='district_trgm',
                opclasses=['gin_trgm_ops']
            ),
        ),
    ]
