# Generated by Django 6.0.2 on 2026-04-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0003_home_district_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
