# Generated by Django 6.0.2 on 2026-04-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0004_home_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
