# Generated by Django 6.0.2 on 2026-04-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0006_alter_home_description_alter_home_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=50, null=True),
        ),
    ]
