# Generated by Django 6.0.2 on 2026-04-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0008_propertyview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='bathrooms_descrip',
        ),
        migrations.RemoveField(
            model_name='home',
            name='bedrooms_descrip',
        ),
        migrations.RemoveField(
            model_name='home',
            name='kitchen_descrip',
        ),
        migrations.RemoveField(
            model_name='home',
            name='livingroom_descrip',
        ),
    ]
