# Generated by Django 6.0.2 on 2026-02-25 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_chatgroup_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessages',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='User.chatgroup'),
        ),
    ]
