# Generated by Django 6.0.2 on 2026-03-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_groupmessages_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessages',
            options={'ordering': ['created']},
        ),
    ]
